# Generated by Django 5.0.6 on 2025-08-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
